# ####################################
# plugin runner
# ####################################
[[plugins]]
repo = 'vlime/vlime'
on_ft = 'lisp'
hook_add = '''
  source ~/.config/nvim/plugins/vlime.vim
'''

