# ####################################
# vim display
# ####################################

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'


# ####################################
# developper plugins 
# ####################################

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# ####################################
# Utility
# ####################################
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

