# ####################################
# lazy plugins
# ####################################
# [[plugins]]
# repo = 'vlime/vlime'
# on_ft = 'lisp'
# rtp = 'vim'

# [[plugins]]
# repo = 'l04m33/vlime'
# on_ft = 'lisp'
# rtp = 'vim'
# hook_add = '''
#   source ~/.config/nvim/plugins/vlime.vim
# '''

[[plugins]]
repo = 'kovisoft/slimv'
on_ft = 'lisp'
hook_add = '''
  source ~/.config/nvim/plugins/slime.vim
'''


