# ####################################
# markdown
# ####################################

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_add = '''
  source ~/.config/nvim/plugins/previm
'''

