# ####################################
# vim display
# ####################################

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

# ####################################
# developper plugins 
# ####################################

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
if = '''executable('node') && executable('yarn')'''
build = './install.sh nightly'
hook_source = 'call coil398#init#coc#hook_source()'
hook_add = '''
  source ~/.config/nvim/plugins/coc.nvim
'''

# ####################################
# Utility
# ####################################

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

