# ####################################
# lazy plugins
# ####################################
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = 'lisp'
hook_add = '''
  source ~/.config/nvim/plugins/slime.vim
'''


