# ####################################
# lazy plugins
# ####################################
# [[plugins]]
# repo = 'l04m33/vlime'
# on_ft = 'lisp'
# rtp = 'vim'
# hook_add = '''
#   source ~/.config/nvim/plugins/vlime.vim
# '''

 [[plugins]]
repo = 'kovisof/slime'
on_ft = 'lisp'
hook_add = '''
  source ~/.config/nvim/plugins/slime.vim
 '''


