# ####################################
# vim display
# ####################################

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/plugins/winresizer.nvim
'''

####################################
# developper plugins 
####################################
# [[plugins]]
# repo = 'neovim/nvim-lsp'
# hook_add = '''
#   source ~/.config/nvim/plugins/nvim-lsp.vim
# '''
 
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  source ~/.config/nvim/plugins/vim-lsp.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  source ~/.config/nvim/plugins/vim-lsp-settings.vim
'''
merged = 0

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  source ~/.config/nvim/plugins/asyncomplete.vim
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# ####################################
# Utility
# ####################################
# [[plugins]]
# repo = "Shougo/denite.nvim"
# hook_add = '''
#   source ~/.config/nvim/plugins/denite.vim
# '''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

# ####################################
# language
# ####################################
[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
  source ~/.config/nvim/plugins/vim-vue.vim
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
  source ~/.config/nvim/plugins/vim-prettier.vim
'''

